import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'necklace-aurora-001',
    title: 'Aurora Diamond Necklace',
    slug: 'aurora-diamond-necklace',
    brand: 'Aurelia Atelier',
    price: 12950.0,
    currency: 'USD',
    description: '18K rose gold necklace with VS clarity diamonds. Handmade in Italy.',
    longDescription:
      'The Aurora Diamond Necklace is a masterpiece of modern design and timeless elegance. Featuring a constellation of brilliant-cut diamonds set in polished 18K rose gold, this piece captures the ethereal beauty of the dawn. Each diamond is hand-selected for its exceptional fire and sparkle, creating a breathtaking display of light. Perfect for momentous occasions or as a signature piece, the Aurora necklace is a testament to superior craftsmanship.',
    collections: ['bridal', 'best-sellers'],
    variants: [
      {
        id: 'aurora-001-18k-rose',
        metal: '18k Rose Gold',
        price: 12950.0,
        sku: 'AUR-001-18R',
        inventory: 5,
        modelUrl: 'gs://aurelia-assets/models/aurora-001.glb',
        previewImage: 'https://placehold.co/800x800.png',
        materialOverrides: { metalness: 1.0, roughness: 0.25 },
        hotspots: [
          {
            id: 'center-stone',
            label: 'Center Diamond - 0.75ct',
            uv: [0.34, 0.56],
            cameraPreset: 'closeup-gem',
          },
        ],
      },
      {
        id: 'aurora-001-platinum',
        metal: 'Platinum',
        price: 14500.0,
        sku: 'AUR-001-PL',
        inventory: 3,
        modelUrl: 'gs://aurelia-assets/models/aurora-001-plat.glb',
        previewImage: 'https://placehold.co/800x800.png',
        materialOverrides: { metalness: 1.0, roughness: 0.1 },
        hotspots: [],
      },
    ],
    seo: {
      title: 'Aurora Diamond Necklace — Aurelia Atelier',
      description: 'Shop the Aurora Diamond Necklace. 18K rose gold, VS diamonds.',
      ogImage: 'gs://aurelia-assets/seo/aurora-og.jpg',
    },
    createdAt: 1690000000000,
  },
  {
    id: 'ring-solitaire-002',
    title: 'Solitaire Engagement Ring',
    slug: 'solitaire-engagement-ring',
    brand: 'Aurelia Atelier',
    price: 9800.0,
    currency: 'USD',
    description: 'Classic platinum solitaire ring with a 1.25ct brilliant diamond.',
    longDescription: 'Embodying pure love and commitment, our Classic Solitaire Engagement Ring is the epitome of grace. A single, magnificent 1.25 carat diamond is held aloft in a sleek, four-prong platinum setting that enhances its natural brilliance. The band, crafted from the finest platinum, offers a timeless appeal and enduring strength. This is more than a ring; it is a promise of forever.',
    collections: ['bridal', 'rings'],
    variants: [
      {
        id: 'sol-002-plat',
        metal: 'Platinum',
        price: 9800.0,
        sku: 'SOL-002-PL',
        inventory: 10,
        modelUrl: 'gs://aurelia-assets/models/sol-002.glb',
        previewImage: 'https://placehold.co/800x800.png',
        materialOverrides: { metalness: 1.0, roughness: 0.1 },
        hotspots: [],
      },
    ],
    seo: {
      title: 'Solitaire Engagement Ring — Aurelia Atelier',
      description: 'The perfect platinum solitaire engagement ring.',
      ogImage: 'gs://aurelia-assets/seo/solitaire-og.jpg',
    },
    createdAt: 1691000000000,
  },
  {
    id: 'earrings-luna-003',
    title: 'Luna Pearl Earrings',
    slug: 'luna-pearl-earrings',
    brand: 'Aurelia Atelier',
    price: 4500.0,
    currency: 'USD',
    description: '18K yellow gold earrings with Akoya pearls and diamond accents.',
    longDescription:
      'Inspired by the serene glow of the moon, the Luna Pearl Earrings are a vision of delicate beauty. Lustrous Akoya pearls are suspended from graceful 18K yellow gold hooks, each adorned with a trio of sparkling diamonds. Their gentle sway and radiant luster make them a sophisticated choice for any ensemble, transitioning effortlessly from day to night.',
    collections: ['best-sellers', 'earrings'],
    variants: [
      {
        id: 'luna-003-18y',
        metal: '18k Yellow Gold',
        price: 4500.0,
        sku: 'LUN-003-18Y',
        inventory: 8,
        modelUrl: 'gs://aurelia-assets/models/luna-003.glb',
        previewImage: 'https://placehold.co/800x800.png',
        materialOverrides: { metalness: 1.0, roughness: 0.2 },
        hotspots: [],
      },
    ],
    seo: {
      title: 'Luna Pearl Earrings — Aurelia Atelier',
      description: 'Elegant Akoya pearl and diamond earrings.',
      ogImage: 'gs://aurelia-assets/seo/luna-og.jpg',
    },
    createdAt: 1692000000000,
  },
  {
    id: 'bracelet-serpent-004',
    title: 'Serpent Bracelet',
    slug: 'serpent-bracelet',
    brand: 'Aurelia Atelier',
    price: 18200.0,
    currency: 'USD',
    description: 'A winding serpent bracelet in 18K gold with emerald eyes.',
    longDescription: 'A symbol of wisdom and eternal love, the Serpent Bracelet coils sensually around the wrist. Crafted from supple 18K yellow gold, its scales are intricately detailed to catch the light. Two mesmerizing emeralds form the serpent\'s eyes, adding a flash of vibrant color. This bold and captivating piece is a true statement of power and style.',
    collections: ['exotics'],
    variants: [
      {
        id: 'serp-004-18y',
        metal: '18k Yellow Gold',
        price: 18200.0,
        sku: 'SERP-004-18Y',
        inventory: 2,
        modelUrl: 'gs://aurelia-assets/models/serp-004.glb',
        previewImage: 'https://placehold.co/800x800.png',
        materialOverrides: { metalness: 1.0, roughness: 0.2 },
        hotspots: [],
      },
    ],
    seo: {
      title: 'Serpent Bracelet — Aurelia Atelier',
      description: 'A bold and beautiful serpent bracelet with emeralds.',
      ogImage: 'gs://aurelia-assets/seo/serpent-og.jpg',
    },
    createdAt: 1693000000000,
  },
  {
    id: 'pendant-celeste-005',
    title: 'Celeste Sapphire Pendant',
    slug: 'celeste-sapphire-pendant',
    brand: 'Aurelia Atelier',
    price: 7850.0,
    currency: 'USD',
    description: 'A deep blue sapphire pendant surrounded by a halo of diamonds.',
    longDescription:
      'The Celeste Sapphire Pendant mirrors the depth of the midnight sky. At its heart lies a magnificent, deep blue sapphire, renowned for its velvety color and exceptional clarity. A sparkling halo of micro-pavé diamonds enhances the sapphire\'s allure, all set in cool, elegant platinum. This pendant is a timeless heirloom, destined to be cherished for generations.',
    collections: ['best-sellers'],
    variants: [
       {
        id: 'cel-005-plat',
        metal: 'Platinum',
        price: 7850.0,
        sku: 'CEL-005-PL',
        inventory: 7,
        modelUrl: 'gs://aurelia-assets/models/cel-005.glb',
        previewImage: 'https://placehold.co/800x800.png',
        materialOverrides: { metalness: 1.0, roughness: 0.1 },
        hotspots: [],
      },
      {
        id: 'cel-005-18y',
        metal: '18k Yellow Gold',
        price: 7500.0,
        sku: 'CEL-005-18Y',
        inventory: 4,
        modelUrl: 'gs://aurelia-assets/models/cel-005-gold.glb',
        previewImage: 'https://placehold.co/800x800.png',
        materialOverrides: { metalness: 1.0, roughness: 0.2 },
        hotspots: [],
      },
    ],
    seo: {
      title: 'Celeste Sapphire Pendant — Aurelia Atelier',
      description: 'A breathtaking sapphire and diamond halo pendant.',
      ogImage: 'gs://aurelia-assets/seo/celeste-og.jpg',
    },
    createdAt: 1694000000000,
  },
];

export const collections = [
  { id: 'all', name: 'All' },
  { id: 'best-sellers', name: 'Best Sellers' },
  { id: 'bridal', name: 'Bridal' },
  { id: 'rings', name: 'Rings' },
  { id: 'earrings', name: 'Earrings' },
  { id: 'exotics', name: 'Exotics' },
];

export const metals = [
  { id: 'all', name: 'All' },
  { id: '18k-rose-gold', name: '18k Rose Gold' },
  { id: 'platinum', name: 'Platinum' },
  { id: '18k-yellow-gold', name: '18k Yellow Gold' },
];
